.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GJIG 1 "February  9, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gjig \- Simplified graphics administrator for Debian
.SH SYNOPSIS
.B gjig
.RI [ options ] " commands" ...
.SH DESCRIPTION
This manual page briefly documents the
.B gjig
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBJIG\fP packages into one tool many commands useful for managing a
Debian system. Instead of having to remember whether to use dpkg or
apt-get or apt-cache, etc, JIG does the selection of the appropriate
tool for you.
.PP
\fBgjig\fP is a user command but will use \fBsudo\fP to run commands
requiring super user permissions if required.
.PP
The primary documentation is available within \fBgjig\fP or \fBwajig help\fP.

.SH SEE ALSO
wajig

.SH AUTHOR
This manual page was written by Graham Williams <Graham.Williams@togaware.com>,
for the Debian GNU/Linux system (but may be used by others).
