.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH wajig 1 "March, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wajig \- Simplified command line administrator for Debian
.SH SYNOPSIS
.B wajig
.RI [ options ] " commands" ...
.SH DESCRIPTION
This manual page briefly documents the
.B wajig
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBwajig\fP packages into one tool many commands useful for managing a
Debian system. Instead of having to remember whether to use dpkg or
apt-get or apt-cache, etc, wajig does the selection of the appropriate
tool for you.
.PP
\fBwajig\fP is a user command but will use \fBsudo\fP to run commands
requiring super user permissions.
.PP
The primary documentation is available from http://www.togaware.com/wajig.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options to get you started is included below.
For more details see \fBwajig tutorial\fP and \fBwajig commands\fP.
.TP
.B \-h, \-\-help
Show summary.
.TP
.B \-V, \-\-version
Show version of program.
.SH AUTHOR
This manual page was written by Graham Williams <Graham.Williams@togaware.com>,
for the Debian GNU/Linux system (but may be used by others).
